<a href="https://colab.research.google.com/github/AmaraRao19/support-ticket-auto-tagging/blob/main/AutoTaggingSupportTickets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Install Required Libraries

In [1]:
!pip install transformers datasets torch scikit-learn

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cpu)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.25.2)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.8.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.4)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.2.25)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)

#Create or Load Dataset

In [2]:
import pandas as pd

data = {
    "text": [
        "I can't login to my account",
        "Payment failed but money deducted",
        "App is crashing on startup",
        "I forgot my password",
        "Unable to update profile",
        "Order not delivered yet",
        "Refund not received",
        "Website is too slow",
        "Error while uploading file",
        "Account got hacked"
    ],
    "label": [
        "Login Issue",
        "Payment Issue",
        "Bug",
        "Login Issue",
        "Profile Issue",
        "Delivery Issue",
        "Refund Issue",
        "Performance Issue",
        "Bug",
        "Security Issue"
    ]
}

df = pd.DataFrame(data)
df

                                text              label
0        I can't login to my account        Login Issue
1  Payment failed but money deducted      Payment Issue
2         App is crashing on startup                Bug
3               I forgot my password        Login Issue
4           Unable to update profile      Profile Issue
5            Order not delivered yet     Delivery Issue
6                Refund not received       Refund Issue
7                Website is too slow  Performance Issue
8         Error while uploading file                Bug
9                 Account got hacked     Security Issue

#Define Possible Tags

In [3]:
labels = list(df['label'].unique())
labels

['Login Issue',
 'Payment Issue',
 'Bug',
 'Profile Issue',
 'Delivery Issue',
 'Refund Issue',
 'Performance Issue',
 'Security Issue']

#Zero-Shot Classification using LLM

In [4]:
from transformers import pipeline

classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/515 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

#Test Zero-Shot Prediction

In [7]:
text = "My payment was deducted but order not placed"

result = classifier(text, labels, multi_label=True)

print("result:")
result

result:

{'sequence': 'My payment was deducted but order not placed',
 'labels': ['Delivery Issue',
  'Payment Issue',
  'Refund Issue',
  'Security Issue',
  'Profile Issue',
  'Performance Issue',
  'Bug',
  'Login Issue'],
 'scores': [0.9649190902709961,
  0.9522677063941956,
  0.625981867313385,
  0.6010469794273376,
  0.4969300627708435,
  0.3566759526729584,
  0.20361021161079407,
  0.1435333490371704]}

#Get Top 3 Tags

In [8]:
def get_top_3(result):
    labels_scores = list(zip(result['labels'], result['scores']))
    sorted_labels = sorted(labels_scores, key=lambda x: x[1], reverse=True)
    return sorted_labels[:3]

get_top_3(result)

[('Delivery Issue', 0.9649190902709961),
 ('Payment Issue', 0.9522677063941956),
 ('Refund Issue', 0.625981867313385)]

#Apply to Full Dataset

In [9]:
df['predictions'] = df['text'].apply(lambda x: get_top_3(classifier(x, labels, multi_label=True)))

df

,text,label,predictions
0,I can't login to my account,Login Issue,"[(Login Issue, 0.9938158988952637), (Security ..."
1,Payment failed but money deducted,Payment Issue,"[(Payment Issue, 0.993032693862915), (Delivery..."
2,App is crashing on startup,Bug,"[(Performance Issue, 0.9807319641113281), (Bug..."
3,I forgot my password,Login Issue,"[(Security Issue, 0.9930335879325867), (Login ..."
4,Unable to update profile,Profile Issue,"[(Profile Issue, 0.9920870065689087), (Bug, 0...."
5,Order not delivered yet,Delivery Issue,"[(Delivery Issue, 0.994367778301239), (Payment..."
6,Refund not received,Refund Issue,"[(Refund Issue, 0.9929617047309875), (Payment ..."
7,Website is too slow,Performance Issue,"[(Performance Issue, 0.9663904309272766), (Log..."
8,Error while uploading file,Bug,"[(Bug, 0.9795052409172058), (Performance Issue..."
9,Account got hacked,Security Issue,"[(Security Issue, 0.9923350811004639), (Bug, 0..."

#Few-Shot Learning (Prompt Engineering)

In [12]:
def few_shot_prompt(text):
    prompt = f"""
    Classify the support ticket into categories.

    Examples:
    Text: I can't login
    Tags: Login Issue

    Text: Payment failed
    Tags: Payment Issue

    Text: {text}
    Tags:
    """
    return prompt

Test:

In [13]:
classifier(few_shot_prompt("App crashes when I open it"), labels)

{'sequence': "\n    Classify the support ticket into categories.\n\n    Examples:\n    Text: I can't login\n    Tags: Login Issue\n\n    Text: Payment failed\n    Tags: Payment Issue\n\n    Text: App crashes when I open it\n    Tags:\n    ",
 'labels': ['Login Issue',
  'Payment Issue',
  'Bug',
  'Security Issue',
  'Performance Issue',
  'Profile Issue',
  'Delivery Issue',
  'Refund Issue'],
 'scores': [0.844735860824585,
  0.10675210505723953,
  0.030698103830218315,
  0.004848987329751253,
  0.004651790950447321,
  0.004115833900868893,
  0.0022504141088575125,
  0.0019469248363748193]}

#Compare Results

In [14]:
zero_shot = classifier("App crashes frequently", labels)
few_shot = classifier(few_shot_prompt("App crashes frequently"), labels)

print("Zero-shot:", get_top_3(zero_shot))
print("Few-shot:", get_top_3(few_shot))

Zero-shot: [('Performance Issue', 0.5116540789604187), ('Bug', 0.2455562949180603), ('Profile Issue', 0.07075708359479904)]
Few-shot: [('Login Issue', 0.8602973818778992), ('Payment Issue', 0.09369863569736481), ('Bug', 0.028001854196190834)]

#Save Notebook

In [15]:
df.to_csv("predictions.csv", index=False)